name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on: [push, workflow_dispatch]

env:
  FOO: baz

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ env.FOO }}
      - run: echo ${{ secrets.FOO_SECRET }}
      - run: echo "Hello World"
        if: ${{ env.FOO == 'bar' }}
